Header tags for tronc ads
INN/umbrella-voiceofoc pull request #18
Opened 2017-05-10 16:10 UTC by kaylima

Added the header tags provided by tronc to serve their ads (body tags to be added to widgets).

2017-05-11 15:31 UTC, rclachance requested changes

2017-05-11 15:31 UTC, rclations commented on wp-content/themes/voiceofoc/functions.php
> +	<script async='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>
you can remove this one - duplicate of ln115

2017-05-15 17:52 UTC, kaylima commented
@rclations the duplicates should be removed. Can you please re-review? Thanks!

2017-05-15 19:42 UTC, rclachance approved these changes

2017-05-15 19:43 UTC, merged